### ISSUE TITLE
Webpage link in About section

### ISSUE THREAD

**Issue by SinghCoder** [oskardudycz/ArchitectureWeekly#55]
Hey @oskardudycz, the link in about section of the repository does not work, probably because it misses www in its url (which seems strange to me)
I am not sure if it is something being blocked by my browser without www or what, but I tried on chrome and brave on my laptop and on chrome on Android, but it is same behaviour across three.
Could you have a look if you are also facing the issue?
If yes, you could probably change to add www in the url.
I am attaching screenshots of without and with www in chrome on pc.

## Without www in the url

![without_www](https://user-images.githubusercontent.com/32142363/146872038-119e6a44-326d-41b9-8e02-f863a04d79b6.png)

## With www in the url

![with_www](https://user-images.githubusercontent.com/32142363/146872058-7c6a0fe6-c7fd-467d-8808-a948e76504d1.png)

**Comment by oskardudycz** [comment]
@SinghCoder, thank you, for sending info about it! The link is fixed by adding the `www.`. I need to play with domain configuration to see why the regular ulr is broken.

**Comment by SinghCoder** [comment]
Sure, if possible, do update in the comment on what was the issue exactly..

**Comment by oskardudycz** [comment]
@SinghCoder, will do. My current guess is some missing DNS entry, but I'll send feedback afterwards 👍

**Comment by micici** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
nicedays233, @willcsw, @harish24x7, @jaanus, @konidev20, @rusrushal13, @acehcks, @ShlokPM1798, @dskmh, @ryboe, @vsouhrada, @antronsilvester, @RedTechKnight, @SSSRaviCharan, @uptutu, @kai-tub, @whoerau, @taramakage, @this-is-mike, @tbrasington

**Comment by SinghCoder** [comment]
@oskardudycz , closing this issue to avoid stale issues.. Don't know if you managed to find the root cause.. If you did, providing your learning would help me here.. If not, no worries.. Thanks!!
